### PR TITLE
Update to Rocket 0.5-rc.1

### PR DESCRIPTION
**Pull request by ELD**
Just as it says. Use the 0.5-rc.1 version of Rocket.

### CODE REVIEW

**Comment by lawliet89** [comment]
Thanks @ELD! Might need to fix some clippy lints about unnecessary borrows.

**Comment by ELD** [comment]
@lawliet89 Just fixed up the Clippy lint error and pushed over the original commit.

**Comment by lawliet89** [comment]
Apparently more to fix. Anyway you can just use your admin "ovewrride" to merge it in when you're happy 😛

**Comment by ELD** [comment]
Damn! I even re-ran Clippy after the fix. Eh, I’ll pay more attention the next time I attempt it and then merge it in.

**Comment by ELD** [comment]
Hm. Doesn't look like I can override the review requirement on the PR or on the master branch. Either way, it's all fixed up and good to merge!

**Review by lawliet89 — APPROVED** [review]

**Comment by lawliet89** [comment]
OK, maybe this is due to how personal Github repos work.

**Pull request merged**
